Traceback (most recent call last):
  File "/Users/Sniper/coding/sniper1211.github.io/automateWithPython/Chapter10/errorExample.py", line 7, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
